# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

char_df = data.frame(A = c("A", "B"),
                     B = c("D", "B"))

test_that("get_mean_data works", {
  expect_true(inherits(get_mean_data, "function"))
  expect_message(get_mean_data(char_df), "char_df doesn't have any numeric cols") 
})
