# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand



vex_x = c(1, 2, 3)
test_that("get_info_data works", {
  expect_true(inherits(get_info_data, "function"))
  expect_error(get_info_data("mydata"), '"mydata" is not a data frame')
  expect_error(get_info_data(vex_x), "vex_x is not a data frame")
})
