# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

#' Title A function that returns the dimensions and name of a data frame
#' 
#' Description Given a data frame it returms a list of the names of the df and dimensions
#' 
#' @param data_frame Function takes a data frame 
#' @return A list  of 2 dimensions and names of data frame
#' 
#' @export
#' 
#' @examples
#' get_info_data(iris)
get_info_data <- function(data_frame){
  
  if(isFALSE(is.data.frame(data_frame))){
    obj_nm = deparse(substitute(data_frame))
    msg = sprintf("%s is not a data frame", obj_nm)
    stop(msg)
  }
  
  nms_df = names(data_frame)
  dim_df = dim(data_frame)
  
  list(dimension = dim_df,
       names = nms_df)
  
}
