# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

#' Title Functions gives the mean of numerics columns of a df
#' 
#' Description
#' @param data_frame A data.frame 
#' @return a data frame / message indicating whether there was numeric cols found
#' @importFrom dplyr summarise_if
#' @export
#' @examples
#' get_mean_data(iris)
#' 
#' char_df = data.frame(A = c("A", "B"),
#'                      B = c("D", "B"))
#' 
#' 
#' get_mean_data(char_df)
get_mean_data <- function(data_frame){
  
  obj_nm = deparse(substitute(data_frame))
  
  if(isFALSE(is.data.frame(data_frame))){
    msg = sprintf("%s is not a data frame", obj_nm)
    stop(msg)
  }
  
  df_output = summarise_if(data_frame, is.numeric, mean, na.rm = T)
  n_col = ncol(df_output)
  
  if(isTRUE(n_col == 0)){
    
    msg = sprintf("%s doesn't have any numeric cols", obj_nm)
    message(msg)
    
  }
  
  
  df_output
  
}
